apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-cover
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-cover
  template:
    metadata:
      labels:
       app: web-cover
    spec:
      containers:
        - name: web-server-cover
          image: rajgandhi123/css-repo:cover
          ports:
            - containerPort: 80