apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-glass
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-glass
  template:
    metadata:
      labels:
       app: web-glass
    spec:
      containers:
        - name: web-server-glass
          image: rajgandhi123/css-repo:glass
          ports:
            - containerPort: 80